### ISSUE TITLE
Minimum Viable Product (MVP)

### ISSUE THREAD

**Issue by gitond** [gitond/graph_alg_test_env#27]
In order to make this project at least somewhat presentable for May the 10th the following steps need to be done at least:
- [x] finish the graph visualisation tasklist at #15 (you can ignore GitHub Actions integration for now)
- [x] file to program graph loading, planning and implementation according to #18 
--- At least two Algorithm modules need to be finished, one of them needs to be Dijkstra. ---
- [x] Plan these two modules at #7 
- [x] Implement Dijkstra module according to #28 
- [ ] Implement BFS module according to #29
